id: P004499
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG018
  title: རུ་ཏྲའི་འཕྲུལ་རྫོང
  author: ''
  volumes:
    2afb5c44c799457ea1930a23e83c06f5:
      image_group_id: I1CZ103
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
